### ISSUE TITLE
Deterministism

### ISSUE THREAD

**Issue by Ericson2314** [clash-lang/ghc-typelits-natnormalise#2]
When I rebuild (with cabal), I get lines like

```
[ 4 of 34] Compiling CLaSH.Promoted.Nat ( src/CLaSH/Promoted/Nat.hs, dist/build/CLaSH/Promoted/Nat.o ) [GHC.TypeLits.Normalise changed]
```

every time. I assume this means there is something non-deterministic going on (or GHC just assumes the worst).

**Comment by christiaanb** [comment]
I have observed this as well. I don't think it's specific to this plugin, but holds for all. That means one of two things:

1. It's a bug in GHC
2. It's intentional because plugins can perform arbitrary I/O. So for example you could make plugin that doesn't work on Monday morning; in that case compiling the module that depends on the plugin should also fail on Mondays.

Option 1 seems more likely, so I guess further investigations is warranted.

**Comment by cartazio** [comment]
@christiaanb I spoke with duncan recently and both he and I think its probably a GHC issue. 
(i was recently using this plugin myself, but then discovered i didnt need to :) )

**Comment by cartazio** [comment]
worth reporting, though probably at this point can't be cleanedup till post 8.0 major version i suspect :)

**Comment by christiaanb** [comment]
@cartazio Good to know that there are more who also think it's a GHC issue. With regards to reporting: I could report it, but I don't feel like putting in the effort of creating a minimal test case, as this GHC hiccup is not causing any failures as far as I know.

With regards to your use of this plugin: you found another plugin? found out you can just write you code another way? of just stopped using GHC.TypeLits.Nat?

**Comment by cartazio** [comment]
Found that the way I'm using known nats just needs sameNat and gcastwith
because it corresponds with when I need to do a run time check anyways. :)

I do suspect that even hello world with the plugin mentioned would get the
rebuilds.  But I've not tested thst :)

**Comment by ggreif** [comment]
@Ericson2314 https://ghc.haskell.org/trac/ghc/ticket/12567

**Comment by Ericson2314** [comment]
Thanks!

**Comment by christiaanb** [comment]
Fixed by: https://github.com/clash-lang/ghc-typelits-natnormalise/commit/c89a4e1779ba51410ea59bf32d5bc0473b83f00d
