### ISSUE TITLE
Please, support ghc-bignum 1.1 & 1.2

### ISSUE THREAD

**Issue by Anton-Latukha** [clash-lang/ghc-typelits-natnormalise#60]
GHC uses `ghc-bignum` as a boot library.

The GHC `9.0.2` uses the `1.1` version that we requested to publish to Hackage.

The GHC `9.2.1` uses `1.2` version, which is already published.

During Haskell-Language-Server work on GHC 9.2 support encountered:
```
[__5] trying: ghc-typelits-knownnat-0.7.6 (dependency of ghcide *test)
[__6] trying: ghc-typelits-natnormalise-0.7.6 (dependency of
ghc-typelits-knownnat)
[__7] next goal: base (dependency of ghcide)
[__7] rejecting: base-4.16.0.0/installed-4.16.0.0 (conflict:
ghc-typelits-natnormalise => ghc-bignum>=1.0 && <1.1, base =>
ghc-bignum==1.2/installed-1.2)
```

Please, adding support for `1.1` & `1.2` would solve this.

**Comment by Anton-Latukha** [comment]
Thank you.

**Comment by martijnbastiaan** [comment]
I've bumped the bounds for the latest revision, `ghc-typelits-natnormalise-0.7.6`, on Hackage.
