### ISSUE TITLE
Possible unsoundness (the plugin seems to claim that 77 ~ 0)

### ISSUE THREAD

**Issue by Mikolaj** [clash-lang/ghc-typelits-natnormalise#79]
The issue and the repro are described around this comment in the GHC bug tracker: https://gitlab.haskell.org/ghc/ghc/-/issues/23923#note_536386

I'm cloning it here in hopes that perhaps here it'd be easier for the esteemed plugin authors to use me as an eager helper in debugging this (I'm responsible for this monstrous repro and its various mutations that also exhibit this behaviour and I'm blocked in my development by this problem).

Thank you in advance.

**Comment by Mikolaj** [comment]
An extremely humble ping. :)

**Comment by christiaanb** [comment]
Sorry, I don't have a lot of time for investigating these issues. I've made some progress: https://gitlab.haskell.org/ghc/ghc/-/issues/23923#note_543652

**Comment by Mikolaj** [comment]
Thank you for the fixes, workarounds and your help in adding the necessary GHC features to properly handle this. As far as i can tell this is all fixed. Closing.
